services:
  - type: web
    name: dumdoors-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
      - key: MONGO_URI
        value: mongodb+srv://your-mongo-atlas-connection-string
      - key: NEO4J_URI
        value: neo4j+s://your-neo4j-aura-connection
      - key: NEO4J_USERNAME
        value: neo4j
      - key: NEO4J_PASSWORD
        fromDatabase:
          name: neo4j-password
          property: password
      - key: REDIS_URI
        value: redis://your-redis-cloud-connection
      - key: AI_SERVICE_URL
        value: https://dumdoors-ai-service.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: LOG_LEVEL
        value: info
      - key: GIN_MODE
        value: release

  - type: web
    name: dumdoors-ai-service
    env: docker
    dockerfilePath: ./ai-service/Dockerfile
    dockerContext: ./ai-service
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: NEO4J_URI
        value: neo4j+s://your-neo4j-aura-connection
      - key: NEO4J_USERNAME
        value: neo4j
      - key: NEO4J_PASSWORD
        fromDatabase:
          name: neo4j-password
          property: password
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: AI_MODEL_PROVIDER
        value: openai
      - key: LOG_LEVEL
        value: info